import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule } from '@angular/router';
import {PdfViewerComponent} from 'ng2-pdf-viewer';
import { JElearningSharedModule } from '../shared';


/* jhipster-needle-add-entity-module-import - JHipster will add entity modules imports here */

    import {
    entityState,
    CoursComponent,
        ChapitreDialogComponent,
        CoursDeleteDialogComponent,
    CoursDialogComponent,
    CoursDetailComponent,
    QuestionComponent,
    QuestionDeleteDialogComponent,
    QuestionDialogComponent,
    QuestionDetailComponent,
    ExamenComponent,
    ExamenDeleteDialogComponent,
    ExamenDialogComponent,
    ExamenDetailComponent,
    QuizComponent,
    QuizDeleteDialogComponent,
    QuizDialogComponent,
    QuizDetailComponent,
    QuizCompComponent,
    ChapitreComponent,
    ChapitreDeleteDialogComponent,

    ChapitreDetailComponent,
    QuizPopupComponent,
    CoursPopupComponent,
    QuestionPopupComponent,
    ExamenPopupComponent,
    ChapitrePopupComponent,
    QuizDeletePopupComponent,
    CoursDeletePopupComponent,
    QuestionDeletePopupComponent,
    ExamenDeletePopupComponent,
    ChapitreDeletePopupComponent,
    ChapitrePopupService,
    ChapitreService,
    ChapitreResolvePagingParams,
    ExamenPopupService,
    ExamenService,
    ExamenResolvePagingParams,
    QuestionPopupService,
    QuestionService,
    QuestionResolvePagingParams,
    QuizPopupService,
    QuizService,
    QuizResolvePagingParams,
    CoursPopupService,
    CoursService,
    QuizCompService,
    QuizCompResolvePagingParams,
    CoursResolvePagingParams,
     CoursResolve,
     ChapitreResolve,
       ExamenResolve,
        QuestionResolve,
        QuizResolve,
        } from './';
import {UserRouteAccessService} from '../shared/auth/user-route-access-service';

@NgModule({
    imports: [
        JElearningSharedModule,
        RouterModule.forRoot(entityState, { useHash: true }),

        /* jhipster-needle-add-entity-module - JHipster will add entity modules here */
    ],
    declarations: [
        PdfViewerComponent,
        CoursComponent,
      CoursDeleteDialogComponent,
       CoursDialogComponent,
        CoursDetailComponent,
        QuestionComponent,
         QuestionDeleteDialogComponent,
         QuestionDialogComponent,
        QuestionDetailComponent,
        ExamenComponent,
        ExamenDeleteDialogComponent,
        ExamenDialogComponent,
        ExamenDetailComponent,
        QuizComponent,
        QuizDeleteDialogComponent,
         QuizDialogComponent,
        QuizDetailComponent,
        QuizCompComponent,
        ChapitreComponent,
        ChapitrePopupComponent,
         ChapitreDialogComponent,
        ChapitreDeleteDialogComponent,
        ChapitreDetailComponent,
        QuizPopupComponent,
        CoursPopupComponent,
        QuestionPopupComponent,
        ExamenPopupComponent,
        QuizDeletePopupComponent,
        CoursDeletePopupComponent,
        QuestionDeletePopupComponent,
        ExamenDeletePopupComponent,
        ChapitreDeletePopupComponent,
    ],
    entryComponents: [
        CoursComponent,
        CoursDeleteDialogComponent,
        CoursDialogComponent,
        CoursDetailComponent,
        QuestionComponent,
        QuestionDeleteDialogComponent,
        QuestionDialogComponent,
        QuestionDetailComponent,
        ExamenComponent,
        ExamenDeleteDialogComponent,
        ExamenDialogComponent,
        ExamenDetailComponent,
        QuizComponent,
        QuizDeleteDialogComponent,
        QuizDialogComponent,
        QuizDetailComponent,
        QuizCompComponent,
       ChapitreComponent,
      ChapitreDialogComponent,
      ChapitreDeleteDialogComponent,
        ChapitreDetailComponent,
        QuizPopupComponent,
        CoursPopupComponent,
        QuestionPopupComponent,
        ExamenPopupComponent,
       ChapitrePopupComponent,
        QuizDeletePopupComponent,
        CoursDeletePopupComponent,
        QuestionDeletePopupComponent,
        ExamenDeletePopupComponent,
       ChapitreDeletePopupComponent,

    ],
    providers: [
        ChapitreResolve,
        ChapitrePopupService,
        ChapitreService,
        ChapitreResolvePagingParams,
        ExamenPopupService,
        ExamenService,
        ExamenResolvePagingParams,
        QuestionPopupService,
        QuestionService,
        QuestionResolvePagingParams,
        QuizPopupService,
        QuizService,
        QuizResolvePagingParams,
        CoursPopupService,
        CoursService,
        QuizCompService,
        QuizCompResolvePagingParams,
        CoursResolvePagingParams,
        CoursResolve,
        ExamenResolve,
        QuestionResolve,
        QuizResolve,
        UserRouteAccessService

    ],

    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class JElearningEntityModule {}
